# Generated by Django 3.2.4 on 2021-06-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('score_idx', models.IntegerField()),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
            ],
        ),
    ]
